/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 paperworld.glb --shadows -s --instance -i --transform -T 
Files: paperworld.glb [1.69MB] > C:\Users\JDTorreda\OneDrive\Documents\GitHub\personal-portfolio\public\paperworld-transformed.glb [137.39KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/paperworld-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane018.geometry} material={materials.Material} position={[0.082, 0, 1.202]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[0.082, 0, 1.202]} />
      <instancedMesh args={[nodes.Plane005.geometry, nodes.Plane005.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Plane005.instanceMatrix} />
      <instancedMesh args={[nodes.Plane.geometry, nodes.Plane.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Plane.instanceMatrix} />
      <instancedMesh args={[nodes.Plane001.geometry, nodes.Plane001.material, 21]} castShadow receiveShadow instanceMatrix={nodes.Plane001.instanceMatrix} />
      <instancedMesh args={[nodes.Plane003.geometry, nodes.Plane003.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Plane003.instanceMatrix} />
      <instancedMesh args={[nodes.Plane006.geometry, nodes.Plane006.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Plane006.instanceMatrix} />
      <instancedMesh args={[nodes.Plane004.geometry, nodes.Plane004.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Plane004.instanceMatrix} />
      <instancedMesh args={[nodes.Plane007.geometry, nodes.Plane007.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Plane007.instanceMatrix} />
      <instancedMesh args={[nodes.Plane009.geometry, nodes.Plane009.material, 7]} castShadow receiveShadow instanceMatrix={nodes.Plane009.instanceMatrix} />
      <instancedMesh args={[nodes.Plane010.geometry, nodes.Plane010.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Plane010.instanceMatrix} />
      <instancedMesh args={[nodes.Plane012.geometry, nodes.Plane012.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Plane012.instanceMatrix} />
      <instancedMesh args={[nodes.Plane013.geometry, nodes.Plane013.material, 13]} castShadow receiveShadow instanceMatrix={nodes.Plane013.instanceMatrix} />
      <instancedMesh args={[nodes.TreeB_TreeB_0.geometry, nodes.TreeB_TreeB_0.material, 20]} castShadow receiveShadow instanceMatrix={nodes.TreeB_TreeB_0.instanceMatrix} />
      <instancedMesh args={[nodes.TreeG_TreeG_0.geometry, nodes.TreeG_TreeG_0.material, 14]} castShadow receiveShadow instanceMatrix={nodes.TreeG_TreeG_0.instanceMatrix} />
      <instancedMesh args={[nodes.TreeC_TreeC_0.geometry, nodes.TreeC_TreeC_0.material, 9]} castShadow receiveShadow instanceMatrix={nodes.TreeC_TreeC_0.instanceMatrix} />
      <instancedMesh args={[nodes.TreeA_TreeA_0.geometry, nodes.TreeA_TreeA_0.material, 9]} castShadow receiveShadow instanceMatrix={nodes.TreeA_TreeA_0.instanceMatrix} />
      <instancedMesh args={[nodes.TreeF_TreeF_0.geometry, nodes.TreeF_TreeF_0.material, 8]} castShadow receiveShadow instanceMatrix={nodes.TreeF_TreeF_0.instanceMatrix} />
      <instancedMesh args={[nodes.Bushes_Bushes_0.geometry, nodes.Bushes_Bushes_0.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Bushes_Bushes_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder002.geometry, nodes.Cylinder002.material, 19]} castShadow receiveShadow instanceMatrix={nodes.Cylinder002.instanceMatrix} />
      <instancedMesh args={[nodes.Plane017.geometry, materials.paper, 246]} castShadow receiveShadow instanceMatrix={nodes.Plane017.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder001.geometry, nodes.Cylinder001.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Cylinder001.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder001_1.geometry, nodes.Cylinder001_1.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Cylinder001_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder001_2.geometry, nodes.Cylinder001_2.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Cylinder001_2.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder004.geometry, nodes.Cylinder004.material, 18]} castShadow receiveShadow instanceMatrix={nodes.Cylinder004.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder004_1.geometry, nodes.Cylinder004_1.material, 18]} castShadow receiveShadow instanceMatrix={nodes.Cylinder004_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder.geometry, nodes.Cylinder.material, 11]} castShadow receiveShadow instanceMatrix={nodes.Cylinder.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder_1.geometry, nodes.Cylinder_1.material, 11]} castShadow receiveShadow instanceMatrix={nodes.Cylinder_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder_2.geometry, nodes.Cylinder_2.material, 11]} castShadow receiveShadow instanceMatrix={nodes.Cylinder_2.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/paperworld-transformed.glb')
